tests: fix bash scripts mistakes

diff --git a/tests/_utils/file_should_exist b/tests/_utils/file_should_exist
--- a/tests/_utils/file_should_exist
+++ b/tests/_utils/file_should_exist
@@ -3,5 +3,5 @@
 set -eu
 
 if [ ! -f "$1" ]; then
-  echo "[$(date)] Directory $1 not found." && exit 1
+  echo "[$(date)] File $1 not found." && exit 1
 fi
